algoritmo "semnome"


var
   R, US : Real



inicio

      EscrevaL("Quantos Reais tu tens na carteira? ")
      Leia(R)
      
      US <- R/3,45
      
      Escreva("Voce pode comprar US",US, " com R$",R)
      
      


fimalgoritmo

//9)	Faça um algoritmo que leia quanto dinheiro uma pessoa tem na carteira
//(em R$) e mostre quantos dólares ela pode comprar. Considere US$1,00 = R$3,45.
