//11)	Desenvolva uma lógica que leia os valores de A, B e C de
//uma equação do segundo grau e mostre o valor de Delta.

algoritmo "semnome"



var


    A, B, C, delta : Real


inicio

      EscrevaL("Digite o valor de A : ")
      Leia(A)
      EscrevaL("Digite o valor de B : ")
      Leia(B)
      EscrevaL("Digite o valor de C ")
      Leia(C)
      
      delta <- (B*B) - (4*A*C)
      
      Escreva("O valor de delta e ", delta)







fimalgoritmo
