//Crie um programa que tenha uma função Media(), que vai receber as 2 notas de
//um aluno e retornar a sua média para o programa principal

algoritmo "semnome"

var

m, n : real


Funcao  media ( m, n : real) : real

inicio

      Retorne (m + n)/2
      
FimFuncao

inicio

      EscrevaL("Informe primeira nota: ")
      Leia(m)
      EscrevaL("Informe segunda nota: ")
      Leia(n)
      EscrevaL("Sua media = ", media(m, n))
      
fimalgoritmo
