//Refaça o exercício 90, só que agora em forma de função Somador(), que vai
//receber dois parâmetros e vai retornar o resultado da soma entre eles para o
//programa principal


algoritmo "Ex095"

var

x, y, z :inteiro

Funcao Somador( m, n: inteiro ): inteiro

Inicio

REtorne m + n

FimFuncao

inicio

EscrevaL ("Digite o primeiro valor: ")
Leia (y)
EscrevaL ("Digite o segundo valor: ")
Leia (z)
X := Somador(y ,z)
EscrevaL ( "A soma é: ", x)

fimalgoritmo

