algoritmo "ex091"
var

N1, N2 : Inteiro

Procedimento Maior (A, B : Inteiro)
Var


Inicio

       Se (A > B) Entao
         Escreva (A, " é maior!")
       Senao
         Se (B > A) Entao
            Escreva (B, " é maior!")
         Senao
         Escreva ("Iguais")
         FimSe
       FimSe

FimProcedimento

inicio

Escreva ("Entre com o primeiro valor: ")
Leia (N1)
Escreva ("Entre com o segundo valor: ")
Leia (N2)

Maior(N1, N2)

fimalgoritmo
