algoritmo "semnome"



var

   x, y, soma : Inteiro
   
Procedimento  Soma(A, B : Inteiro)
Inicio
      EscrevaL("Voce digitou x = ", A)
      EscrevaL("E voce digitou y = ", B)
      EscrevaL("A soma deles vale =", A + B)


Fimprocedimento

inicio

//X := 5
//y := 6
//soma := x + y
//EscrevaL("A soma foi de ", soma)

Escreva("Digite um valor :")
Leia(x)
Escreva("Escreva outro valor :")
Leia(y)
Soma(x,y)
//Escreva("A soma de x + y =", soma)


fimalgoritmo
